# Generated by Django 4.2.26 on 2025-11-25 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("questions", "0005_alter_question_options_alter_answer_user_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="avatar",
            field=models.ImageField(
                blank=True, null=True, upload_to="", verbose_name="Аватарка"
            ),
        ),
    ]
