# Generated by Django 4.2.26 on 2025-11-29 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("questions", "0006_alter_userprofile_avatar"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="text",
            field=models.TextField(blank=True, verbose_name="Текст"),
        ),
    ]
